# Generated by Django 5.1.3 on 2024-11-29 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weatherpreferences", "0002_weatherpreferences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherpreferences",
            old_name="cloud_lover",
            new_name="sun_lover",
        ),
        migrations.RenameField(
            model_name="weatherpreferences",
            old_name="wind",
            new_name="wind_hater",
        ),
    ]
