# Generated by Django 5.1.3 on 2024-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherpreferences", "0004_healthconditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherfeedback",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="cloud_cover",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="precipitation_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="precipitation_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="temperature_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="temperature_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="wind_angle",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="wind_dir",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="LocationHistory",
        ),
    ]
