# Generated by Django 5.1.3 on 2024-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "weatherpreferences",
            "0005_weatherfeedback_city_weatherfeedback_cloud_cover_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherfeedback",
            name="icon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
