# Generated by Django 5.1.3 on 2025-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherpreferences", "0007_journalentry_useractions"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_precipitation_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_precipitation_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_temperature_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_temperature_avg_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_temperature_avg_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_temperature_record_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_temperature_record_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_wind_avg_angle",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_wind_avg_dir",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_wind_avg_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_wind_max_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherfeedback",
            name="stats_wind_max_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
