# Generated by Django 5.1.3 on 2025-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherpreferences", "0009_alter_weatherpreferences_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherpreferences",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
