# Generated by Django 5.1.3 on 2025-03-01 12:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction pour la page du blog"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="language",
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Contenu de l'article"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(help_text="Résumé de l'article", max_length=250),
        ),
    ]
