# Generated by Django 5.1.3 on 2025-03-03 15:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogindexpage_remove_blogpage_cover_image_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image principale de l'article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(
                help_text="Contenu détaillé de l'article"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(help_text="Résumé de l'article", max_length=500),
        ),
    ]
