# Generated by Django 5.1.3 on 2025-03-10 15:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogpage_header_image_alter_blogpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("html", 1), ("script", 3)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "image",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                            ]
                        },
                    ),
                    1: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide the relative path to your JavaScript file (e.g., 'js/quiz.js')"
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("script_url", 2)]], {}),
                },
            ),
        ),
    ]
