# Generated by Django 5.1.3 on 2024-11-23 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("weather", models.CharField(max_length=50)),
                ("temperature", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("temperature_max", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.CharField(max_length=10)),
                ("cloud_cover", models.FloatField()),
                ("precipitation_total", models.FloatField()),
                ("precipitation_type", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
