# Generated by Django 5.1.3 on 2024-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyforecast",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="dailyforecast",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="dailyforecast",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="dailyforecast",
            name="wind_direction",
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="icon",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="moon_phase",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="moonrise",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="moonset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_precipitation_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_precipitation_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_temperature_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_temperature_avg_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_temperature_avg_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_temperature_record_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_temperature_record_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_wind_avg_angle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_wind_avg_dir",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_wind_avg_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_wind_max_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="stats_wind_max_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="sunrise",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="sunset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="wind_angle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyforecast",
            name="wind_dir",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="cloud_cover",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="precipitation_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="precipitation_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="temperature_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="temperature_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="weather",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
