# Generated by Django 5.1.3 on 2024-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0002_remove_dailyforecast_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyforecast",
            name="cloud_cover",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="precipitation_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="stats_wind_avg_angle",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="stats_wind_avg_dir",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="wind_angle",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyforecast",
            name="wind_dir",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
