# Generated by Django 5.1.3 on 2024-11-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0006_alter_dailyforecast_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyforecast",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dailyforecasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
