# Generated by Django 5.1.3 on 2024-11-29 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0007_alter_dailyforecast_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeatherFeedback",
        ),
    ]
