# Generated by Django 5.1.3 on 2024-12-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0008_delete_weatherfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_system",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("metric", "Metric (°C, mm/h, m/s)"),
                            ("us", "Imperial (°F, in/h, mph)"),
                            ("uk", "UK (metric with mph/miles)"),
                            ("ca", "Canadian (metric with km/h and kPa)"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
