# Generated by Django 5.1.3 on 2024-12-26 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0009_forecastsetting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForecastSetting",
        ),
    ]
