# Generated by Django 5.1.3 on 2024-12-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0010_delete_forecastsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyforecast",
            name="day_length",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
