# Generated by Django 5.1.3 on 2025-02-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapi", "0011_dailyforecast_day_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_max_diff_from_avg", models.FloatField(blank=True, null=True)),
                (
                    "wind_ave_speed_diff_from_avg",
                    models.FloatField(blank=True, null=True),
                ),
                ("consecutive_cloudy_days", models.IntegerField(default=0)),
                ("consecutive_sunny_days", models.IntegerField(default=0)),
                ("consecutive_rainy_days", models.IntegerField(default=0)),
                (
                    "forecast",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="weatherapi.dailyforecast",
                    ),
                ),
            ],
        ),
    ]
