# Generated by Django 5.1.3 on 2024-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0003_locationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="likes_rain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_temperature_max",
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_temperature_min",
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sun_worshipper",
            field=models.BooleanField(default=True),
        ),
    ]
