# Generated by Django 5.1.3 on 2024-11-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0004_userprofile_likes_rain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="home_town",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
