# Generated by Django 5.1.3 on 2024-11-28 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0005_userprofile_home_town"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="home_town",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="likes_rain",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_temperature_max",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_temperature_min",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sun_worshipper",
        ),
        migrations.DeleteModel(
            name="LocationHistory",
        ),
    ]
