# Generated by Django 5.1.3 on 2024-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0006_remove_userprofile_home_town_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hometown",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
