# Generated by Django 5.1.3 on 2024-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0007_userprofile_hometown"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
