# Generated by Django 5.1.3 on 2024-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0008_userprofile_is_first_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_first_login",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="units",
            field=models.CharField(
                choices=[
                    ("metric", "Metric"),
                    ("us", "US"),
                    ("uk", "UK"),
                    ("ca", "Canada"),
                ],
                default="metric",
                max_length=10,
            ),
        ),
    ]
