# Generated by Django 5.1.3 on 2025-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0010_userprofile_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
