# Generated by Django 5.1.3 on 2025-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0011_alter_userprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
