# Generated by Django 5.1.3 on 2025-01-30 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0012_alter_userprofile_latitude_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
