# Generated by Django 5.1.3 on 2025-01-30 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authenticate", "0013_delete_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hometown", models.TextField(blank=True, max_length=100)),
                ("lat", models.FloatField(blank=True)),
                ("lon", models.FloatField(blank=True)),
                (
                    "units",
                    models.CharField(
                        choices=[
                            ("metric", "Metric"),
                            ("us", "US"),
                            ("uk", "UK"),
                            ("ca", "Canada"),
                        ],
                        default="metric",
                        max_length=10,
                    ),
                ),
                ("first_login", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
