# Generated by Django 5.1.3 on 2025-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0014_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
