# Generated by Django 5.1.3 on 2025-02-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0015_alter_profile_lat_alter_profile_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hometown_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="weather_preferences_completed",
            field=models.BooleanField(default=False),
        ),
    ]
