# Generated by Django 5.1.3 on 2025-02-18 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0018_profile_current_location_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="longitude",
            new_name="lon",
        ),
    ]
