# Generated by Django 5.1.3 on 2025-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0019_rename_latitude_location_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
    ]
