# Generated by Django 5.1.3 on 2025-02-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0020_alter_location_end_date_alter_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                blank=True,
                choices=[("vacation", "Vacation"), ("hometown", "Hometown")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="authenticate.profile",
            ),
        ),
    ]
